apiVersion: v1
kind: Service
metadata:
    name: "aksaqakslab-d167"
    labels:
        app: "aksaqakslab-d167"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksaqakslab-d167"